services:
  - type: web
    name: asset-extractors-web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: PORT
        value: 3000
